server:
  port: 3340
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: morelliApplication
  profiles:
    active: dev


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect